
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qltrlxgodfltejixardl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFsdHJseGdvZGZsdGVqaXhhcmRsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjUyMjgsImV4cCI6MjA2MzQwMTIyOH0.dKyEnpnqFL0rwak3fk9l_SLuqVMSlq_BG__Pd547ZWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create the typed client
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Create a custom type for our portfolio table
export type PortfolioTable = {
  id: string;
  expert_id: string;
  template_id: string;
  education: any[];
  experience: any[];
  skills: any[];
  achievements: string[];
  created_at: string;
  updated_at: string;
};

// Create helper functions for expert_portfolios table operations
// Fixing TypeScript issues by using the direct table name in each function
export const expertPortfoliosTable = {
  select: () => {
    return supabase.from('expert_portfolios');
  },
  update: (data: Partial<PortfolioTable>) => {
    return supabase.from('expert_portfolios').update(data);
  },
  insert: (data: Partial<PortfolioTable>) => {
    return supabase.from('expert_portfolios').insert(data);
  },
  delete: () => {
    return supabase.from('expert_portfolios').delete();
  }
};
